theme = "dark_plus"


[editor]
line-number = "relative"
bufferline = "multiple"
true-color = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"up" = "no_op"
"down" = "no_op"
"left" = "no_op"
"right" = "no_op"

[editor.cursor-shape]
insert = "bar"

 