

[editor]
scrolloff=15
auto-format=false
cursorline = true
rulers = [1, 10]
bufferline = "always"
color-modes = true
#gutters = ["spacer", "spacer", "spacer", "diagnostics",]
#line-number = "no_op"


[editor.gutters]
layout = ["spacer", "spacer", "spacer", "spacer", "spacer", "spacer", "spacer","spacer", "spacer", ]


[keys.normal]
esc = "no_op"  


[keys.normal."+"]
s = [":write", ":config-reload"] # Comment

[editor.file-picker]
hidden = false

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"


